<?php

namespace App\Http\Requests\Products;

use Illuminate\Foundation\Http\FormRequest;

final class CreateProductRequest extends FormRequest
{
    /**
     * @OA\Schema(
     *  title="Create Product",
     *  description="Create Product request",
     *  schema="CreateProductRequestSchema",
     *  required={"name", "description", "price"},
     *  @OA\Property(
     *      property="name.hy",
     *      type="string",
     *      example="Name in Armenian",
     *      title="Name in Armenian."
     *  ),
     *  @OA\Property(
     *      property="name.ru",
     *      type="string",
     *      example="Name in Russian",
     *      title="Name in Russian."
     *  ),
     *  @OA\Property(
     *      property="name.ena",
     *      type="string",
     *      example="Name in English",
     *      title="Name in English."
     *  ),
     *  @OA\Property(
     *      property="description.hy",
     *      type="string",
     *      example="Desciption in Armenian",
     *      title="Desciption in Armenian."
     *  ),
     *  @OA\Property(
     *      property="description.ru",
     *      type="string",
     *      example="Desciption in Russian",
     *      title="Desciption in Russian."
     *  ),
     *  @OA\Property(
     *      property="description.ena",
     *      type="string",
     *      example="Desciption in English",
     *      title="Desciption in English."
     *  ),
     *  @OA\Property(
     *      property="price",
     *      type="number",
     *      example="1000"
     *  ),
     * )
     *
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'name' => [
                'required',
                'array',
            ],
            'name.hy' => [
                'required',
                'string',
            ],
            'name.ru' => [
                'required',
                'string',
            ],
            'name.en' => [
                'required',
                'string',
            ],
            'description' => [
                'required',
                'array',
            ],
            'description.hy' => [
                'required',
                'string',
            ],
            'description.ru' => [
                'required',
                'string',
            ],
            'description.en' => [
                'required',
                'string',
            ],
            'price' => [
                'required',
                'numeric',
            ],
        ];
    }

    /**
     * @OA\Schema(
     *  title="Create Product",
     *  description="Create Product validation messages",
     *  schema="CreateProductRequestMessagesSchema",
     *  @OA\Property(
     *      property="name.hy",
     *      type="string",
     *      example={"The id field is required.", "The selected id is invalid."},
     *  ),
     *  @OA\Property(
     *      property="name.ru",
     *      type="string",
     *      example={"The id field is required.", "The selected id is invalid."},
     *  ),
     *  @OA\Property(
     *      property="name.en",
     *      type="string",
     *      example={"The id field is required.", "The selected id is invalid."},
     *  ),
     *  @OA\Property(
     *      property="description.hy",
     *      type="string",
     *      example={"The id field is required.", "The selected id is invalid."},
     *  ),
     *  @OA\Property(
     *      property="description.ru",
     *      type="string",
     *      example={"The id field is required.", "The selected id is invalid."},
     *  ),
     *  @OA\Property(
     *      property="description.en",
     *      type="string",
     *      example={"The id field is required.", "The selected id is invalid."},
     *  ),
     *  @OA\Property(
     *      property="price",
     *      type="string",
     *      example={"The count field is required.", "The count should be a numeric."}
     *  )
     * )
     *
     * Get the validation messages that apply to the request.
     *
     * @return array
     */
    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
